branches:
  - 'main'
plugins:
  - - '@semantic-release/commit-analyzer'
    - preset: conventionalcommits
  - '@semantic-release/release-notes-generator'
  - '@semantic-release/changelog'
  - 'semantic-release-license'
  - - '@semantic-release/git'
    - assets:
        - CHANGELOG.md
        - LICENSE
  - '@semantic-release/github'