plugins:
  - - '@semantic-release/commit-analyzer'
    - preset: conventionalcommits
  - '@semantic-release/release-notes-generator'
  - '@semantic-release/changelog'
  - - '@semantic-release/git'
    - assets:
        - CHANGELOG.md
  - - '@semantic-release/github'
    - assets:
        - path: "output/cv.pdf"
          label: "Curriculum vitae"
        